export const CLASSIC_PLAYLIST = [
    { file: '174-Mozart-Symphony-No40-1st.mp3', name: '[モーツァルト] 交響曲第40番' },
    { file: 'Beethoven-Symphony-No5-1st.mp3', name: '[ベートーヴェン] 運命' },
    { file: 'Brahms-HungarianDances-No5.mp3', name: '[ブラームス] ハンガリー舞曲 第5番' },
    { file: 'Chopin-Fantaisie-Impromptu-2019-AR.mp3', name: '[ショパン] 幻想即興曲' },
    { file: 'Chopin-Nocturn-No2-2013.mp3', name: '[ショパン] ノクターン第2番' },
    { file: 'Chopin-Poronase-No6-Heroic-2019-AR.mp3', name: '[ショパン] 英雄ポロネーズ' },
    { file: 'Chopin-Revolutional.mp3', name: '[ショパン] 革命のエチュード' },
    { file: 'Debussy-Arabesque-No1-2014.mp3', name: '[ドビュッシー] アラベスク第1番' },
    { file: 'Debussy-clairdelune.mp3', name: '[ドビュッシー] 月の光' },
    { file: 'dovorak-Symphony-No9-4th.mp3', name: '[ドヴォルザーク] 新世界より' },
    { file: 'Elgar-Pomp-and-Circumstance-No1.mp3', name: '[エルガー] 威風堂々' },
    { file: 'Elgar-Salut-damour-2019-AR.mp3', name: '[エルガー] 愛の挨拶' },
    { file: 'J.S.Bach-G-air.mp3', name: '[J.S.バッハ] G線上のアリア' },
    { file: 'Johann-Strauss-2-The-Blue-Danube.mp3', name: '[ヨハン・シュトラウス2世] 美しく青きドナウ' },
    { file: 'Liszt-LaCampanella-2020-AR.mp3', name: '[リスト] ラ・カンパネラ' },
    { file: 'Liszt-Liebestraum-No3.mp3', name: '[リスト] 愛の夢 第3番' },
    { file: 'Mozart-EineKleine-1st.mp3', name: '[モーツァルト] アイネ・クライネ・ナハトムジーク' },
    { file: 'Mozart_ALLA_TURCA.mp3', name: '[モーツァルト] トルコ行進曲' },
    { file: 'Pachelbel-Canon-in-D-2019-AR.mp3', name: '[パッヘルベル] カノン' },
    { file: 'Tchaikovsky-Nutcracker-waltz-flowers.mp3', name: '[チャイコフスキー] 花のワルツ' },
    { file: 'The_Garden_s_Final_Ascent.mp3', name: '[Gs Eye] The Garden\'s Final Ascent' },
    { file: 'Vivaldi-4Seasons-Winter-1st.mp3', name: '[ヴィヴァルディ] 四季より"冬"' },
    { file: '乙女の祈りバダジェフスカBadarzewskaLa prière d\'une viergeピアノpianoCANACANA.mp3', name: '[バダジェフスカ] 乙女の祈り' },
    { file: '渚のアデリーヌリチャードクレイダーマンBallade Pour AdelineRichard Clayderman.mp3', name: '[リチャード・クレイダーマン] 渚のアデリーヌ' },
    { file: 'Chopin-Prelude-No15-Raindrop.mp3', name: '[ショパン] 雨だれの前奏曲' },
    { file: 'Satie-Gymnopedies-No1-piano.mp3', name: '[サティ] ジムノペディ第1番' },
    { file: 'J.S.Bach-Herz-und-Mund-und-Tat-und-Leben.mp3', name: '[J.S.バッハ] 主よ、人の望みの喜びよ' },
    { file: 'Toccata and Fugue in D Minor (Best Version).mp3', name: '[J.S.バッハ] トッカータとフーガ ニ短調' },
    { file: 'Beethoven-MoonlightSonata-1.mp3', name: '[ベートーヴェン] 月光ソナタ 第1楽章' },
    { file: 'Beethoven - Für Elise.mp3', name: '[ベートーヴェン] エリーゼのために' },
    { file: 'Tchaikovsky-TheNutcracker-March-2019-AR.mp3', name: '[チャイコフスキー] くるみ割り人形より「行進曲」' },
    { file: 'Tchaikovsky-SwanLake-act2-Seane-AR.mp3', name: '[チャイコフスキー] 白鳥の湖より「情景」' },
    { file: '023-Sibelius-Finlandia.mp3', name: '[シベリウス] フィンランディア' },
    { file: 'Richard-Strauss-Also-sprach-Zarathustra-Einleitung-2019-AR.mp3', name: '[R.シュトラウス] ツァラトゥストラはかく語りき' },
    { file: 'Grieg-PeerGynt-In-the-Hall-of-the-Mountain-King-2016.mp3', name: '[グリーグ] 山の魔王の宮殿にて' },
    { file: 'Edvard Grieg_ Peer Gynt - Morning Mood.mp3', name: '[グリーグ] ペール・ギュントより「朝」' },
    { file: 'Holst-The-Planets-Jupiter-Thaxted.mp3', name: '[ホルスト] 木星（ジュピター）' },
    { file: 'Ravel-Borelo.mp3', name: '[ラヴェル] ボレロ' },
    { file: 'Ludwig van Beethoven_ Ode an die FreudeOde to Joy 1.mp3', name: '[ベートーヴェン] 歓喜の歌（第9交響曲）' },
    { file: 'Chopin_ 12 Etudes, Op. 10_ No. 3 in E Major Tristesse.mp3', name: '[ショパン] 別れの曲' },
    { file: 'Chopin - Minute Waltz (Op. 64 No. 1).mp3', name: '[ショパン] 子犬のワルツ' },
    // === ここから追加分（第3弾 13曲） ===
    { file: '208-Liszt-Hungarian-Rhapsodies-No2.mp3', name: '[リスト] ハンガリー狂詩曲 第2番' },
    { file: 'Mussorgsky_ Pictures at an Exhibition (Orch. Ravel) _ Promenade 1.mp3', name: '[ムソルグスキー] 展覧会の絵より「プロムナード」' },
    { file: 'Kreisler_ Liebesfreud.mp3', name: '[クライスラー] 愛の喜び' },
    { file: 'Rossini-William-Tell-Overture-Liszt-Piano-Timpani.mp3', name: '[ロッシーニ／リスト編曲] ウィリアム・テル序曲（ピアノ版）' },
    { file: 'Rossini-William-Tell-Overture-2020-AR.mp3', name: '[ロッシーニ] ウィリアム・テル序曲' },
    { file: '065-Tchaikovsky-PianoConcerto-No1-1st-Intro.mp3', name: '[チャイコフスキー] ピアノ協奏曲 第1番' },
    { file: 'Smetana-The-Moldau-2013.mp3', name: '[スメタナ] モルダウ（ヴルタヴァ）' },
    { file: 'Gershwin-Rhapsody-in-Blue.mp3', name: '[ガーシュウィン] ラプソディ・イン・ブルー' },
    { file: 'Mendelssohn-WeddingMarch-2020-AR.mp3', name: '[メンデルスゾーン] 結婚行進曲' },
    { file: 'JohannStraussI-Radetzky-Marsch-2019-AR.mp3', name: '[J.シュトラウス1世] ラデツキー行進曲' },
    { file: 'Massenet-Meditation.mp3', name: '[マスネ] タイスの瞑想曲' },
    { file: '028-Schubert-Die-Forelle.mp3', name: '[シューベルト] 鱒（ます）' },
    { file: 'Ave Maria, Op. 52 No. 6, D. 839.mp3', name: '[シューベルト] アヴェ・マリア' },
    // === ここまで ===
    // === ここから追加分（第4弾 13曲） ===
    { file: 'Wagner-Die-Meistersinger-von-Nuernberg-Vorspiel-act1-2019-AR.mp3', name: '[ワーグナー] マイスタージンガー 第1幕前奏曲' },
    { file: '218-Wagner-Lohengrin-Wedding-March.mp3', name: '[ワーグナー] ローエングリンより「婚礼の合唱」' },
    { file: 'Wagner-Ride-of-the-Valkyries-2015.mp3', name: '[ワーグナー] ワルキューレの騎行' },
    { file: 'Mozart-Symphony-No25-1st-2015.mp3', name: '[モーツァルト] 交響曲第25番 第1楽章' },
    { file: 'Vivaldi-The-Four-Seasons-Autumn-1st.mp3', name: '[ヴィヴァルディ] 四季より"秋"第1楽章' },
    { file: 'Vivaldi-FourSeasons-LEstate-3rd-2020-AR.mp3', name: '[ヴィヴァルディ] 四季より"夏"第3楽章' },
    { file: 'Vivaldi-The-Four-Seasons-Spring-1st-2012-2.mp3', name: '[ヴィヴァルディ] 四季より"春"第1楽章' },
    { file: '007-Verdi-La-Traviata-Libiamo.mp3', name: '[ヴェルディ] 椿姫より「乾杯の歌」' },
    { file: 'Puccini-Turandot.mp3', name: '[プッチーニ] トゥーランドット（誰も寝てはならぬ）' },
    { file: 'Offenbach_ Orpheus in the Underworld_ Overture.mp3', name: '[オッフェンバック] 天国と地獄 序曲' },
    { file: 'Mozart-Marriage-of-Figaro-Overture-2016.mp3', name: '[モーツァルト] フィガロの結婚 序曲' },
    { file: '114-Bizet-Carmen-Air-de-Toreador.mp3', name: '[ビゼー] カルメンより「闘牛士の歌」' },
    { file: 'Carmen - Habanera (Bizet Anna Caterina Antonacci, The Royal Opera).mp3', name: '[ビゼー] カルメンより「ハバネラ」' },
    { file: 'The_Last_eye_Departure.mp3', name: '[Gs Eye] The Last eye Departure' }
    // === ここまで ===
];
