export const CLASSIC_PLAYLIST = [
    { file: '174-Mozart-Symphony-No40-1st.mp3', name: '[モーツァルト]\n交響曲第40番' },
    { file: 'Beethoven-Symphony-No5-1st.mp3', name: '[ベートーヴェン]\n運命' },
    { file: 'Brahms-HungarianDances-No5.mp3', name: '[ブラームス]\nハンガリー舞曲 第5番' },
    { file: 'Chopin-Fantaisie-Impromptu-2019-AR.mp3', name: '[ショパン]\n幻想即興曲' },
    { file: 'Chopin-Nocturn-No2-2013.mp3', name: '[ショパン]\nノクターン第2番' },
    { file: 'Chopin-Poronase-No6-Heroic-2019-AR.mp3', name: '[ショパン]\n英雄ポロネーズ' },
    { file: 'Chopin-Revolutional.mp3', name: '[ショパン]\n革命のエチュード' },
    { file: 'Debussy-Arabesque-No1-2014.mp3', name: '[ドビュッシー]\nアラベスク第1番' },
    { file: 'Debussy-clairdelune.mp3', name: '[ドビュッシー]\n月の光' },
    { file: 'dovorak-Symphony-No9-4th.mp3', name: '[ドヴォルザーク]\n新世界より' },
    { file: 'Elgar-Pomp-and-Circumstance-No1.mp3', name: '[エルガー]\n威風堂々' },
    { file: 'Elgar-Salut-damour-2019-AR.mp3', name: '[エルガー]\n愛の挨拶' },
    { file: 'J.S.Bach-G-air.mp3', name: '[J.S.バッハ]\nG線上のアリア' },
    { file: 'Johann-Strauss-2-The-Blue-Danube.mp3', name: '[ヨハン・シュトラウス2世]\n美しく青きドナウ' },
    { file: 'Liszt-LaCampanella-2020-AR.mp3', name: '[リスト]\nラ・カンパネラ' },
    { file: 'Liszt-Liebestraum-No3.mp3', name: '[リスト]\n愛の夢 第3番' },
    { file: 'Mozart-EineKleine-1st.mp3', name: '[モーツァルト]\nアイネ・クライネ・\nナハトムジーク' },
    { file: 'Mozart_ALLA_TURCA.mp3', name: '[モーツァルト]\nトルコ行進曲' },
    { file: 'Pachelbel-Canon-in-D-2019-AR.mp3', name: '[パッヘルベル]\nカノン' },
    { file: 'Tchaikovsky-Nutcracker-waltz-flowers.mp3', name: '[チャイコフスキー]\n花のワルツ' },
    { file: 'The_Garden_s_Final_Ascent.mp3', name: '[Gs Eye]\nThe Garden\'s Final Ascent' },
    { file: 'Vivaldi-4Seasons-Winter-1st.mp3', name: '[ヴィヴァルディ]\n四季より"冬"' },
    { file: '乙女の祈りバダジェフスカBadarzewskaLa prière d\'une viergeピアノpianoCANACANA.mp3', name: '[バダジェフスカ]\n乙女の祈り' },
    { file: '渚のアデリーヌリチャードクレイダーマンBallade Pour AdelineRichard Clayderman.mp3', name: '[リチャード・クレイダーマン]\n渚のアデリーヌ' },
    { file: 'Chopin-Prelude-No15-Raindrop.mp3', name: '[ショパン]\n雨だれの前奏曲' },
    { file: 'Satie-Gymnopedies-No1-piano.mp3', name: '[サティ]\nジムノペディ第1番' },
    { file: 'J.S.Bach-Herz-und-Mund-und-Tat-und-Leben.mp3', name: '[J.S.バッハ]\n主よ、人の望みの\n喜びよ' },
    { file: 'Toccata and Fugue in D Minor (Best Version).mp3', name: '[J.S.バッハ]\nトッカータとフーガ\nニ短調' },
    { file: 'Beethoven-MoonlightSonata-1.mp3', name: '[ベートーヴェン]\n月光ソナタ 第1楽章' },
    { file: 'Beethoven - Für Elise.mp3', name: '[ベートーヴェン]\nエリーゼのために' },
    { file: 'Tchaikovsky-TheNutcracker-March-2019-AR.mp3', name: '[チャイコフスキー]\nくるみ割り人形より\n「行進曲」' },
    { file: 'Tchaikovsky-SwanLake-act2-Seane-AR.mp3', name: '[チャイコフスキー]\n白鳥の湖より「情景」' },
    { file: '023-Sibelius-Finlandia.mp3', name: '[シベリウス]\nフィンランディア' },
    { file: 'Richard-Strauss-Also-sprach-Zarathustra-Einleitung-2019-AR.mp3', name: '[R.シュトラウス]\nツァラトゥストラは\nかく語りき' },
    { file: 'Grieg-PeerGynt-In-the-Hall-of-the-Mountain-King-2016.mp3', name: '[グリーグ]\n山の魔王の宮殿にて' },
    { file: 'Edvard Grieg_ Peer Gynt - Morning Mood.mp3', name: '[グリーグ]\nペール・ギュントより「朝」' },
    { file: 'Holst-The-Planets-Jupiter-Thaxted.mp3', name: '[ホルスト]\n木星（ジュピター）' },
    { file: 'Ravel-Borelo.mp3', name: '[ラヴェル]\nボレロ' },
    { file: 'Ludwig van Beethoven_ Ode an die FreudeOde to Joy 1.mp3', name: '[ベートーヴェン]\n歓喜の歌（第9交響曲）' },
    { file: 'Chopin_ 12 Etudes, Op. 10_ No. 3 in E Major Tristesse.mp3', name: '[ショパン]\n別れの曲' },
    { file: 'Chopin - Minute Waltz (Op. 64 No. 1).mp3', name: '[ショパン]\n子犬のワルツ' },
    // === ここから追加分（第3弾 13曲） ===
    { file: '208-Liszt-Hungarian-Rhapsodies-No2.mp3', name: '[リスト]\nハンガリー狂詩曲 第2番' },
    { file: 'Mussorgsky_ Pictures at an Exhibition (Orch. Ravel) _ Promenade 1.mp3', name: '[ムソルグスキー]\n展覧会の絵より\n「プロムナード」' },
    { file: 'Kreisler_ Liebesfreud.mp3', name: '[クライスラー]\n愛の喜び' },
    { file: 'Rossini-William-Tell-Overture-Liszt-Piano-Timpani.mp3', name: '[ロッシーニ／リスト編曲]\nウィリアム・テル序曲\n（ピアノ版）' },
    { file: 'Rossini-William-Tell-Overture-2020-AR.mp3', name: '[ロッシーニ]\nウィリアム・テル序曲' },
    { file: '065-Tchaikovsky-PianoConcerto-No1-1st-Intro.mp3', name: '[チャイコフスキー]\nピアノ協奏曲 第1番' },
    { file: 'Smetana-The-Moldau-2013.mp3', name: '[スメタナ]\nモルダウ（ヴルタヴァ）' },
    { file: 'Gershwin-Rhapsody-in-Blue.mp3', name: '[ガーシュウィン]\nラプソディ・イン・ブルー' },
    { file: 'Mendelssohn-WeddingMarch-2020-AR.mp3', name: '[メンデルスゾーン]\n結婚行進曲' },
    { file: 'JohannStraussI-Radetzky-Marsch-2019-AR.mp3', name: '[J.シュトラウス1世]\nラデツキー行進曲' },
    { file: 'Massenet-Meditation.mp3', name: '[マスネ]\nタイスの瞑想曲' },
    { file: '028-Schubert-Die-Forelle.mp3', name: '[シューベルト]\n鱒（ます）' },
    { file: 'Ave Maria, Op. 52 No. 6, D. 839.mp3', name: '[シューベルト]\nアヴェ・マリア' },
    // === ここまで ===
    // === ここから追加分（第4弾 13曲） ===
    { file: 'Wagner-Die-Meistersinger-von-Nuernberg-Vorspiel-act1-2019-AR.mp3', name: '[ワーグナー]\nマイスタージンガー\n第1幕前奏曲' },
    { file: '218-Wagner-Lohengrin-Wedding-March.mp3', name: '[ワーグナー]\nローエングリンより\n「婚礼の合唱」' },
    { file: 'Wagner-Ride-of-the-Valkyries-2015.mp3', name: '[ワーグナー]\nワルキューレの騎行' },
    { file: 'Mozart-Symphony-No25-1st-2015.mp3', name: '[モーツァルト]\n交響曲第25番 第1楽章' },
    { file: 'Vivaldi-The-Four-Seasons-Autumn-1st.mp3', name: '[ヴィヴァルディ]\n四季より"秋"\n第1楽章' },
    { file: 'Vivaldi-FourSeasons-LEstate-3rd-2020-AR.mp3', name: '[ヴィヴァルディ]\n四季より"夏"\n第3楽章' },
    { file: 'Vivaldi-The-Four-Seasons-Spring-1st-2012-2.mp3', name: '[ヴィヴァルディ]\n四季より"春"\n第1楽章' },
    { file: '007-Verdi-La-Traviata-Libiamo.mp3', name: '[ヴェルディ]\n椿姫より「乾杯の歌」' },
    { file: 'Puccini-Turandot.mp3', name: '[プッチーニ]\nトゥーランドット\n（誰も寝てはならぬ）' },
    { file: 'Offenbach_ Orpheus in the Underworld_ Overture.mp3', name: '[オッフェンバック]\n天国と地獄 序曲' },
    { file: 'Mozart-Marriage-of-Figaro-Overture-2016.mp3', name: '[モーツァルト]\nフィガロの結婚 序曲' },
    { file: '114-Bizet-Carmen-Air-de-Toreador.mp3', name: '[ビゼー]\nカルメンより\n「闘牛士の歌」' },
    { file: 'Carmen - Habanera (Bizet Anna Caterina Antonacci, The Royal Opera).mp3', name: '[ビゼー]\nカルメンより\n「ハバネラ」' },
    { file: 'The_Last_eye_Departure.mp3', name: '[Gs Eye]\nThe Last eye Departure' }
];
